# Generated by Django 2.1.2 on 2018-11-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='할 일의 제목을 입력해중주세요. 최대 100자 이내.', max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('status', models.CharField(choices=[('i', '진행중'), ('c', '완료'), ('e', '기한 초과')], default='i', max_length=1, verbose_name='상태')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일자')),
                ('due_by', models.DateTimeField(blank=True, null=True, verbose_name='마감 기한')),
                ('priority', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
