# Generated by Django 2.1.2 on 2018-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_by',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='마감 날짜'),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='마감 시간'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(help_text='0은 마지막 순위입니다.', verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='할 일의 제목을 입력해주세요. 최대 100자 이내.', max_length=100, verbose_name='제목'),
        ),
    ]
