# Generated by Django 2.1.2 on 2018-11-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20181101_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
